# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_sc_trim_barcode_paired <- function(outfq, r1, r2, bs1, bl1, bs2, bl2, us, ul, rmlow, rmN, minq, numbq, write_gz) {
    invisible(.Call(`_scPipe_rcpp_sc_trim_barcode_paired`, outfq, r1, r2, bs1, bl1, bs2, bl2, us, ul, rmlow, rmN, minq, numbq, write_gz))
}

rcpp_sc_exon_mapping <- function(inbam, outbam, annofn, am, ge, bc, mb, bc_len, bc_vector, UMI_len, stnd, fix_chr, nthreads) {
    invisible(.Call(`_scPipe_rcpp_sc_exon_mapping`, inbam, outbam, annofn, am, ge, bc, mb, bc_len, bc_vector, UMI_len, stnd, fix_chr, nthreads))
}

rcpp_sc_exon_mapping_df_anno <- function(inbam, outbam, anno, am, ge, bc, mb, bc_len, bc_vector, UMI_len, stnd, fix_chr, nthreads) {
    invisible(.Call(`_scPipe_rcpp_sc_exon_mapping_df_anno`, inbam, outbam, anno, am, ge, bc, mb, bc_len, bc_vector, UMI_len, stnd, fix_chr, nthreads))
}

rcpp_sc_demultiplex <- function(inbam, outdir, bc_anno, max_mis, am, ge, bc, mb, mito, has_UMI, nthreads) {
    invisible(.Call(`_scPipe_rcpp_sc_demultiplex`, inbam, outdir, bc_anno, max_mis, am, ge, bc, mb, mito, has_UMI, nthreads))
}

rcpp_sc_clean_bam <- function(inbam, outbam, bc_anno, max_mis, am, ge, bc, mb, mito, nthreads) {
    invisible(.Call(`_scPipe_rcpp_sc_clean_bam`, inbam, outbam, bc_anno, max_mis, am, ge, bc, mb, mito, nthreads))
}

rcpp_sc_gene_counting <- function(outdir, bc_anno, UMI_cor, gene_fl) {
    invisible(.Call(`_scPipe_rcpp_sc_gene_counting`, outdir, bc_anno, UMI_cor, gene_fl))
}

rcpp_sc_detect_bc <- function(infq, outcsv, prefix, bc_len, max_reads, number_of_cells, min_count, max_mismatch, white_list) {
    invisible(.Call(`_scPipe_rcpp_sc_detect_bc`, infq, outcsv, prefix, bc_len, max_reads, number_of_cells, min_count, max_mismatch, white_list))
}

rcpp_sc_atac_trim_barcode <- function(outfq, r1, r3, barcode_file, start, len, umi_start, umi_len, umi_in, write_gz, rmN, rmlow, min_qual, num_below_min, id1_st, id1_len, id2_st, id2_len) {
    invisible(.Call(`_scPipe_rcpp_sc_atac_trim_barcode`, outfq, r1, r3, barcode_file, start, len, umi_start, umi_len, umi_in, write_gz, rmN, rmlow, min_qual, num_below_min, id1_st, id1_len, id2_st, id2_len))
}

rcpp_sc_atac_trim_barcode_paired <- function(outfq, r1, r2_list, r3, write_gz, rmN, rmlow, min_qual, num_below_min, id1_st, id1_len, id2_st, id2_len, umi_start, umi_len) {
    invisible(.Call(`_scPipe_rcpp_sc_atac_trim_barcode_paired`, outfq, r1, r2_list, r3, write_gz, rmN, rmlow, min_qual, num_below_min, id1_st, id1_len, id2_st, id2_len, umi_start, umi_len))
}

rcpp_sc_atac_bam_tagging <- function(inbam, outbam, bc, mb, nthreads) {
    invisible(.Call(`_scPipe_rcpp_sc_atac_bam_tagging`, inbam, outbam, bc, mb, nthreads))
}

rcpp_fasta_bin_bed_file <- function(in_filename, out_filename, bin_size) {
    invisible(.Call(`_scPipe_rcpp_fasta_bin_bed_file`, in_filename, out_filename, bin_size))
}

rcpp_append_chr_to_bed_file <- function(in_filename, out_filename) {
    invisible(.Call(`_scPipe_rcpp_append_chr_to_bed_file`, in_filename, out_filename))
}

