


#' create SCData object from data folder generated by preprocessing step
#' 
#' after we run \code{sc_gene_counting} and finish the preprocessing step. \code{create_scd_by_dir}
#' can be used to generate the SCData obeject from the folder that contains gene counting matrix and QC statistics.
#'
#' @param datadir the directory that contains all the data and `stat` subfolder.
#' @param species the organism of the data. List of possible names can be retrieved using the function 
#' `listDatasets`from `biomaRt` package. (i.e `mmusculus_gene_ensembl` or `hsapiens_gene_ensembl`)
#' @param gene_id gene id type of the data A possible list of ids can be retrieved using the function `listAttributes` from `biomaRt` package. 
#' the commonly used id types are `external_gene_name`, `ensembl_gene_id` or `entrezgene`
#' @param pheno_data the external phenotype data that linked to each single cell. this should be an \code{AnnotatedDataFrame} object
#' 
#' @details after we run \code{sc_gene_counting} and finish the preprocessing step. \code{create_scd_by_dir}
#' can be used to generate the SCData obeject from the folder that contains gene counting matrix and QC statistics.
#' 
#' @return an SCData object
#'
#'
#' @export
#' 

create_scd_by_dir = function(datadir, species=NULL, gene_id=NULL, pheno_data=NULL){
  gene_cnt = read.csv(file.path(datadir, "gene_count.csv"),row.names=1)
  cell_stat = read.csv(file.path(datadir,"stat","cell_stat.csv"),row.names=1)
  
  gene_cnt = gene_cnt[,order(colnames(gene_cnt))]
  cell_stat = cell_stat[order(rownames(cell_stat)),]
  
  
  QualityControlInfo = new("AnnotatedDataFrame", data = as.data.frame(cell_stat))
  scd = newSCData(countData = as.matrix(gene_cnt),
                  QualityControlInfo = QualityControlInfo,
                  phenoData = pheno_data,
                  useForExprs = "counts",
                  organism = species,
                  gene_id_type = gene_id)
  
  return(scd)
}


#' create_report
#' 
#' create html report using data generated by proprocessing step.
#'
#' @param sample_name sample name
#' @param outdir output folder
#' @param r1 file path of read1
#' @param r2 file path of read2 default to be NULL
#' @param outfq file path of the output of \code{sc_trim_barcode}
#' @param read_structure a list contains read structure configuration. for more help see `?sc_trim_barcode`
#' @param filter_settings a list contains read filter settings for more help see `?sc_trim_barcode`
#' @param align_bam the aligned bam file
#' @param genome_index genome index used for alignment
#' @param map_bam the mapped bam file
#' @param exon_anno the gff exon annotation used
#' @param stnd whether to perform strand specific mapping
#' @param fix_chr add `chr` to chromosome names, fix inconsistant names.
#' @param barcode_anno genome annotation, gff file. can have multiple files
#' @param max_mis maximum mismatch allowed in barcode. default to be 1
#' @param UMI_cor correct UMI sequence error: 0 means no correction, 1 means simple correction and merge UMI with distance 1.
#' @param gene_fl whether to remove low abundant gene count. low abundant is defined as only one copy of one UMI for this gene
#' @param species the organism of the data. List of possible names can be retrieved using the function 
#' `listDatasets`from `biomaRt` package. (i.e `mmusculus_gene_ensembl` or `hsapiens_gene_ensembl`)
#' @param gene_id_type gene id type of the data A possible list of ids can be retrieved using the function `listAttributes` from `biomaRt` package. 
#' the commonly used id types are `external_gene_name`, `ensembl_gene_id` or `entrezgene`
#'
#' @export
#'
create_report = function(sample_name,
                         outdir,
                         r1,
                         r2=NULL,
                         outfq,
                         read_structure,
                         filter_settings,
                         align_bam,
                         genome_index,
                         map_bam,
                         exon_anno,
                         stnd,
                         fix_chr,
                         barcode_anno,
                         max_mis,
                         UMI_cor,
                         gene_fl,
                         species,
                         gene_id_type){
  fn = system.file("extdata", "report_template.Rmd", package = "scPipe")
  tx = readLines(fn)
  
  tx = gsub(pattern = "SAMPLE_NAME__", replacement = sample_name, x = tx)
  tx = gsub(pattern = "FQ1__", replacement = r1, x = tx)
  tx = gsub(pattern = "FQ2__", replacement = r2, x = tx)
  tx = gsub(pattern = "FQOUT__", replacement = outfq, x = tx)
  if(read_structure$bs1<0){
    tx = gsub(pattern = "BC1_INFO__", replacement = "NA", x = tx)
    BC1_INFO="NA"
  }else{
    tx = gsub(pattern = "BC1_INFO__", replacement = 
                paste0("start at position ",read_structure$bs1,", length ",read_structure$bl1), x = tx)
  }
  
  tx = gsub(pattern = "BC1_INFO__", replacement = 
              paste0("start at position ",read_structure$bs2,", length ",read_structure$bl2), x = tx)
  tx = gsub(pattern = "UMI_INFO__", replacement = 
              paste0("start at position ",read_structure$us,", length ",read_structure$ul), x = tx)
  
  tx = gsub(pattern = "RM_N__", replacement = as.character(filter_settings$rmN), x = tx)
  tx = gsub(pattern = "RM_LOW__", replacement = as.character(filter_settings$rmlow), x = tx)
  tx = gsub(pattern = "MIN_Q__", replacement = filter_settings$minq, x = tx)
  tx = gsub(pattern = "NUM_BQ__", replacement = filter_settings$numbq, x = tx)
  
  tx = gsub(pattern = "BAM_ALIGN__", replacement = align_bam, x = tx)
  tx = gsub(pattern = "G_INDEX__", replacement = genome_index, x = tx)
  tx = gsub(pattern = "BAM_MAP__", replacement = map_bam, x = tx)
  
  tx = gsub(pattern = "OUTDIR__", replacement = outdir, x = tx)
  tx = gsub(pattern = "ANNO_GFF__", replacement = paste(exon_anno, collapse=","), x = tx)
  
  tx = gsub(pattern = "STND__", replacement = as.character(stnd), x = tx)
  tx = gsub(pattern = "FIX_CHR__", replacement = as.character(fix_chr), x = tx)
  tx = gsub(pattern = "BC_ANNO__", replacement = barcode_anno, x = tx)
  tx = gsub(pattern = "MAX_MIS__", replacement = max_mis, x = tx)
  
  if(UMI_cor == 1){
    tx = gsub(pattern = "UMI_COR__", replacement = "simple correction and merge UMI with distance 1", x = tx)
  }else if(UMI_cor == 0){
    tx = gsub(pattern = "UMI_COR__", replacement = "no correction", x = tx)
  }else{
    tx = gsub(pattern = "UMI_COR__", replacement = "unknown", x = tx)
  }
  
  tx = gsub(pattern = "GENE_FL__", replacement = as.character(gene_fl), x = tx)
  
  tx = gsub(pattern = "SPECIES__", replacement = species, x = tx)
  tx = gsub(pattern = "GENE_ID_TYPE__", replacement = gene_id_type, x = tx)
  
  writeLines(tx, con=file.path(outdir,"report.Rmd"))
  knitr::wrap_rmd(file.path(outdir,"report.Rmd"), width = 120,backup = NULL)
  rmarkdown::render(file.path(outdir,"report.Rmd"), output_file = file.path(outdir,"report.html"))
}